- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # SS220-RoleTime 2
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance
  #SS220 LimitationRevive - start
  special:
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill
  #SS220 LimitationRevive - end

- type: startingGear
  id: ChemistGear
  equipment:
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
#    eyes: ClothingEyesGlassesChemical #SS220-TwoOne-Floppa-Iterations
  #storage:
    #back:
    #- Stuff
