- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600 # SS220-RoleTime 2
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: true
  access:
  - Medical
  - Maintenance
  #SS220 LimitationRevive - start
  special:
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill 
  #SS220 LimitationRevive - end

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: BookMedicalReferenceBook
  #storage:
    #back:
    #- Stuff
