- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # SS220-RoleTime 2
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Paramedic
  extendedAccess:
  - Chemistry
  #SS220 LimitationRevive - start
  special:
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill 
  #SS220 LimitationRevive - end

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
#    belt: ClothingBeltMedicalEMTFilled #ss220 paramedicinterdyne
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
