- type: job
  id: BlueShield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueShield
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # SS220-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 # SS220-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 180000 # SS220-RoleTime
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
  startingGear: BlueShieldGear
  icon: "JobIconBlueShield"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Cargo
  - Atmospherics
  - Cargo
  - Medical
  - Blueshield
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
#  - !type:AddComponentSpecial
#    components:
#      - type: CQCCombat
#        availableSpells:
#        - NonLethalBlowback
#        - NonLethalPunch
#        - NonLethalDisarm
#        - NonLethalLongSleep
#      - type: Missable
  #SS220 LimitationRevive - start
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill 
  #SS220 LimitationRevive - end

- type: startingGear
  id: BlueShieldGear
  equipment:
#    jumpsuit: ClothingUniformJumpsuitBlueShield #SS220-blueshield-loadouts
    shoes: ClothingShoesBootsBlueShieldJackFilled #SS220 BlueShield Rework
#    eyes: ClothingEyesBlueShieldGlasses #SS220 BlueShield Rework
#    head: ClothingHeadHatBeretNavyBlue #SS220 BlueShield Rework
#    outerClothing: ClothingOuterArmorBulletproof #SS220-blueshield-loadouts
    id: BlueShieldPDA
    ears: ClothingHeadsetBlueShield #SS220 BlueShield Rework
    pocket1: WeaponSynergisticEnergyGun #SS220 BlueShield Rework
#    belt: ClothingBeltSecurityFilled #SS220-blueshield-loadouts
    gloves: ClothingHandsGlovesCombat
# SS220-Blueshield-Storage-Fix-Begin
  storage:
    back:
#    - BoxSurvival SS220-Two Floppa Iteration
    - Stunbaton #SS220 BlueShieldReworks
    - Flash
# SS220-Blueshield-Storage-Fix-End
