- type: job
  id: ChiefEngineer
  name: job-name-ce
  description: job-description-ce
  playTimeTracker: JobChiefEngineer
  requirements:
    # SS220 Role requirements begin
    # off
    # - !type:RoleTimeRequirement
    #   role: JobAtmosphericTechnician
    #   time: 9000 #2.5 hrs
    # - !type:RoleTimeRequirement
    #   role: JobStationEngineer
    #   time: 18000 #5 hrs
    # - !type:DepartmentTimeRequirement
    #   department: Engineering
    #   time: 36000 #10 hrs
    # off
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 180000 # SS220-RoleTime
    - !type:AgeRequirement
      requiredAge: 20
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
    # SS220 Role requirements end
  weight: 10
  startingGear: ChiefEngineerGear
  icon: "JobIconChiefEngineer"
  supervisors: job-supervisors-captain
  access:
  - Maintenance
  - Engineering
  - Command
  - External
  - ChiefEngineer
  - Atmospherics
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: DefibrillatorSkill #SS220 LimitationRevive

- type: startingGear
  id: ChiefEngineerGear
  equipment:
#    id: CEPDA SS220-dark-chief-engineer-pda
#    eyes: ClothingEyesGlassesMeson #SS220-TwoOne-Floppa-Iteration
    ears: ClothingHeadsetCE
    belt: ClothingBeltUtilityEngineering
  storage:
    back:
    - Flash
