- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    #SS220 requirements begin
    # off
    # - !type:RoleTimeRequirement
    #   role: JobCargoTechnician
    #   time: 18000 #5 hrs
    # - !type:RoleTimeRequirement
    #   role: JobSalvageSpecialist
    #   time: 9000 #2.5 hrs
    # - !type:DepartmentTimeRequirement
    #   department: Cargo
    #   time: 36000 #10 hours
    # off
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 108000 # SS220-RoleTime
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 18000 # SS220-RoleTime 2
    - !type:OverallPlaytimeRequirement
      time: 180000 # SS220-RoleTime
    - !type:AgeRequirement
      requiredAge: 20
    - !type:SpeciesRequirement #SS220-jobbans begin
      inverted: true
      species:
      - Felinid #SS220-jobbans end
    #SS220 requirements end
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: DefibrillatorSkill #SS220 LimitationRevive

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
