# © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

- type: entity
  name: Оперативник "Синий Щит"
  id: CentCommOperativeBSO
  components:
    - type: Sprite
      sprite: SS220/Markers/jobs.rsi
      state: centcommoperativebs
    - type: RandomHumanoidSpawner
      settings: CentCommOperativeBSO

- type: randomHumanoidSettings
  id: CentCommOperativeBSO
  speciesBlacklist: [ Arachnid, Diona, Dwarf, Reptilian, Skeleton, SlimePerson, Vox, Moth, Felinid, Tajaran]
  components:
    - type: RandomHumanoidAppearance
      randomizeName: false
      hair: HairBald
    - type: RandomMetadata
      nameSegments:
        - NamesFirstBSOMember
        - NamesLastBSOMember
    - type: MindShield
    - type: GhostRole
      name: ghost-role-information-centcom-BSO-name
      description: ghost-role-information-centcom-BSO-description
    - type: GhostTakeoverAvailable
    - type: Loadout
      prototypes: [ CentcomOperativeBSOGear ]

- type: playTimeTracker
  id: JobCentcommOperativeBSO

- type: job
  id: CentcomOperativeBSO
  name: job-name-cc-bs-operative
  description: job-description-centcomoff
  setPreference: false
  startingGear: CentcomOperativeBSOGear
  playTimeTracker: JobCentcommOperativeBSO
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  radioBold: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommandBSO
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill

- type: startingGear
  id: CentcomOperativeBSOGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBlueShieldOperative
    shoes: ClothingShoesBootsBlueShieldJackFilled
    head: ClothingHeadBeretBlueshield
    eyes: ClothingEyesBlueShieldGlasses
    gloves: ClothingHandsGlovesPowergloveDisabler
    outerClothing: ClothingOuterBSOCoat
    id: CentcomOperativeBSOPDA
    ears: ClothingHeadsetAltCentComm
    pocket1: WeaponSynergisticEnergyGun
    pocket2: TelescopicShield
    belt: ClothingBeltBlueShieldFilled
    back: ClothingBackpackBlueShieldHightFilled
