meta:
  format: 6
  postmapinit: false
tilemap:
  0: Space
  65: FloorShuttleWhite
  93: Lattice
  94: Plating
entities:
- proto: ""
  entities:
  - uid: 73
    components:
    - type: MetaData
    - type: Transform
      pos: -2.46875,-1.421875
      parent: invalid
    - type: MapGrid
      chunks:
        0,0:
          ind: 0,0
          tiles: XgAAAAAAQQAAAAAAQQAAAAAAQQAAAAAAXgAAAAAAXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAAAAQQAAAAAAQQAAAAAAQQAAAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAAAAQQAAAAAAQQAAAAAAQQAAAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAAAAQQAAAAAAQQAAAAAAQQAAAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAAAAXgAAAAAAQQAAAAAAXgAAAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXgAAAAAAXgAAAAAAXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          version: 6
        0,-1:
          ind: 0,-1
          tiles: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXQAAAAAAXgAAAAAAQQAAAAAAXgAAAAAAXQAAAAAAXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          version: 6
        -1,0:
          ind: -1,0
          tiles: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
          version: 6
        -1,-1:
          ind: -1,-1
          tiles: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXQAAAAAA
          version: 6
    - type: Broadphase
    - type: Physics
      bodyStatus: InAir
      angularDamping: 0.05
      linearDamping: 0.05
      fixedRotation: False
      bodyType: Dynamic
    - type: Fixtures
      fixtures: {}
    - type: OccluderTree
    - type: Shuttle
    - type: GridPathfinding
    - type: Gravity
      gravityShakeSound: !type:SoundPathSpecifier
        path: /Audio/Effects/alert.ogg
    - type: DecalGrid
      chunkCollection:
        version: 2
        nodes: []
    - type: GridAtmosphere
      version: 2
      data:
        tiles:
          0,0:
            0: 13111
            1: 52424
          0,1:
            1: 239
          1,0:
            1: 4371
          1,1:
            1: 1
          0,-1:
            1: 61440
          1,-1:
            1: 12288
          -1,0:
            1: 8
          -1,-1:
            1: 32768
        uniqueMixes:
        - volume: 2500
          temperature: 293.15
          moles:
          - 21.824879
          - 82.10312
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        - volume: 2500
          temperature: 293.15
          moles:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
        chunkSize: 4
    - type: GasTileOverlay
    - type: RadiationGridResistance
    - type: SpreaderGrid
- proto: AirlockGlassShuttle
  entities:
  - uid: 21
    components:
    - type: Transform
      pos: 2.5,-0.5
      parent: 73
- proto: APCHighCapacity
  entities:
  - uid: 69
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 4.5,0.5
      parent: 73
- proto: CableApcExtension
  entities:
  - uid: 59
    components:
    - type: Transform
      pos: 4.5,0.5
      parent: 73
  - uid: 60
    components:
    - type: Transform
      pos: 3.5,0.5
      parent: 73
  - uid: 61
    components:
    - type: Transform
      pos: 2.5,0.5
      parent: 73
  - uid: 62
    components:
    - type: Transform
      pos: 2.5,1.5
      parent: 73
  - uid: 63
    components:
    - type: Transform
      pos: 2.5,2.5
      parent: 73
  - uid: 64
    components:
    - type: Transform
      pos: 2.5,3.5
      parent: 73
  - uid: 65
    components:
    - type: Transform
      pos: 2.5,4.5
      parent: 73
  - uid: 66
    components:
    - type: Transform
      pos: 1.5,0.5
      parent: 73
- proto: CableHV
  entities:
  - uid: 43
    components:
    - type: Transform
      pos: 0.5,0.5
      parent: 73
  - uid: 44
    components:
    - type: Transform
      pos: 1.5,0.5
      parent: 73
  - uid: 45
    components:
    - type: Transform
      pos: 2.5,0.5
      parent: 73
  - uid: 46
    components:
    - type: Transform
      pos: 2.5,1.5
      parent: 73
  - uid: 47
    components:
    - type: Transform
      pos: 2.5,2.5
      parent: 73
  - uid: 48
    components:
    - type: Transform
      pos: 2.5,3.5
      parent: 73
  - uid: 49
    components:
    - type: Transform
      pos: 1.5,3.5
      parent: 73
  - uid: 50
    components:
    - type: Transform
      pos: 0.5,3.5
      parent: 73
- proto: CableMV
  entities:
  - uid: 51
    components:
    - type: Transform
      pos: 0.5,3.5
      parent: 73
  - uid: 52
    components:
    - type: Transform
      pos: 1.5,3.5
      parent: 73
  - uid: 53
    components:
    - type: Transform
      pos: 2.5,3.5
      parent: 73
  - uid: 54
    components:
    - type: Transform
      pos: 2.5,2.5
      parent: 73
  - uid: 55
    components:
    - type: Transform
      pos: 2.5,1.5
      parent: 73
  - uid: 56
    components:
    - type: Transform
      pos: 2.5,0.5
      parent: 73
  - uid: 57
    components:
    - type: Transform
      pos: 3.5,0.5
      parent: 73
  - uid: 58
    components:
    - type: Transform
      pos: 4.5,0.5
      parent: 73
- proto: ChairPilotSeat
  entities:
  - uid: 30
    components:
    - type: Transform
      rot: 1.5707963267948966 rad
      pos: 1.5,1.5
      parent: 73
  - uid: 31
    components:
    - type: Transform
      rot: 1.5707963267948966 rad
      pos: 1.5,2.5
      parent: 73
  - uid: 32
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 3.5,2.5
      parent: 73
  - uid: 33
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 3.5,1.5
      parent: 73
  - uid: 72
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: 2.5,4.5
      parent: 73
- proto: ClosetEmergencyFilledRandom
  entities:
  - uid: 38
    components:
    - type: Transform
      pos: 1.5,3.5
      parent: 73
    - type: EntityStorage
      air:
        volume: 200
        immutable: False
        temperature: 147.92499
        moles:
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
        - 0
- proto: ClosetFireFilled
  entities:
  - uid: 39
    components:
    - type: Transform
      pos: 3.5,3.5
      parent: 73
- proto: DonkpocketBoxSpawner
  entities:
  - uid: 42
    components:
    - type: Transform
      pos: 3.5,0.5
      parent: 73
- proto: EmergencyLight
  entities:
  - uid: 40
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 3.5,0.5
      parent: 73
    - type: PointLight
      enabled: True
    - type: ActiveEmergencyLight
- proto: GeneratorWallmountAPU
  entities:
  - uid: 68
    components:
    - type: Transform
      pos: 0.5,0.5
      parent: 73
- proto: Grille
  entities:
  - uid: 3
    components:
    - type: Transform
      pos: 0.5,4.5
      parent: 73
  - uid: 4
    components:
    - type: Transform
      pos: 3.5,5.5
      parent: 73
  - uid: 6
    components:
    - type: Transform
      pos: 3.5,4.5
      parent: 73
  - uid: 10
    components:
    - type: Transform
      pos: 2.5,5.5
      parent: 73
  - uid: 11
    components:
    - type: Transform
      pos: 1.5,4.5
      parent: 73
  - uid: 24
    components:
    - type: Transform
      pos: 4.5,4.5
      parent: 73
  - uid: 26
    components:
    - type: Transform
      pos: 1.5,5.5
      parent: 73
- proto: Poweredlight
  entities:
  - uid: 70
    components:
    - type: Transform
      rot: 1.5707963267948966 rad
      pos: 1.5,3.5
      parent: 73
    - type: ApcPowerReceiver
      powerLoad: 0
  - uid: 71
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 3.5,3.5
      parent: 73
    - type: ApcPowerReceiver
      powerLoad: 0
- proto: ShuttleWindow
  entities:
  - uid: 5
    components:
    - type: Transform
      pos: 1.5,5.5
      parent: 73
  - uid: 9
    components:
    - type: Transform
      pos: 0.5,4.5
      parent: 73
  - uid: 25
    components:
    - type: Transform
      pos: 2.5,5.5
      parent: 73
  - uid: 27
    components:
    - type: Transform
      pos: 1.5,4.5
      parent: 73
  - uid: 35
    components:
    - type: Transform
      pos: 3.5,4.5
      parent: 73
  - uid: 36
    components:
    - type: Transform
      pos: 3.5,5.5
      parent: 73
  - uid: 37
    components:
    - type: Transform
      pos: 4.5,4.5
      parent: 73
- proto: SubstationWallBasic
  entities:
  - uid: 67
    components:
    - type: Transform
      pos: 0.5,3.5
      parent: 73
- proto: TableReinforcedGlass
  entities:
  - uid: 29
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 3.5,0.5
      parent: 73
  - uid: 34
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 1.5,0.5
      parent: 73
- proto: Thruster
  entities:
  - uid: 20
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: -0.5,-0.5
      parent: 73
  - uid: 28
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: 5.5,-0.5
      parent: 73
- proto: ToolboxEmergencyFilled
  entities:
  - uid: 41
    components:
    - type: Transform
      pos: 1.515625,0.6490259
      parent: 73
- proto: WallShuttle
  entities:
  - uid: 7
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: 4.5,2.5
      parent: 73
  - uid: 8
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: 4.5,1.5
      parent: 73
  - uid: 14
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 0.5,0.5
      parent: 73
  - uid: 15
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 0.5,3.5
      parent: 73
  - uid: 16
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 4.5,3.5
      parent: 73
  - uid: 17
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 4.5,0.5
      parent: 73
  - uid: 18
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 3.5,-0.5
      parent: 73
  - uid: 19
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 1.5,-0.5
      parent: 73
  - uid: 22
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: 0.5,2.5
      parent: 73
  - uid: 23
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: 0.5,1.5
      parent: 73
- proto: WallShuttleDiagonal
  entities:
  - uid: 1
    components:
    - type: Transform
      rot: 1.5707963267948966 rad
      pos: 0.5,-0.5
      parent: 73
  - uid: 2
    components:
    - type: Transform
      rot: 3.141592653589793 rad
      pos: 4.5,-0.5
      parent: 73
  - uid: 12
    components:
    - type: Transform
      pos: -0.5,0.5
      parent: 73
  - uid: 13
    components:
    - type: Transform
      rot: -1.5707963267948966 rad
      pos: 5.5,0.5
      parent: 73
...
