- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 # SS220-RoleTime
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  #SS220 LimitationRevive - start
  special:
  - !type:AddComponentSpecial
    components:
    - type: DefibrillatorSkill 
  #SS220 LimitationRevive - end

- type: startingGear
  id: PsychologistGear
  equipment:
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
#    - BoxSurvivalMedical #SS220-delete-dupe-box
    - PillCanisterPsycho #SS220-Pills-Psychologist
    - RubberStampPsychologist
