name: "Labels: Changes"

on:
  pull_request_review:
    types: [submitted]

jobs:
  update_label:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      pull-requests: write
      contents: write
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Status: Awaiting Changes"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "Status: Needs Review"
